# Validating QUBO Circuit

Here, we aim to validate that the quantum circuit used to represent a generic Quadratic Unconstrained Binary Optimization (QUBO) problem is indeed equivalent to the corresponding cost function.

In [1]:
try:
    from qaoa import QAOA, problems, mixers, initialstates, util
except ImportError:
    from qaoa import QAOA, problems, mixers, initialstates, util

import os
import sys

from qaoa.util.plotroutines import *
from matplotlib import pyplot as plt
import numpy as np

import itertools

In [2]:
Q = -np.array([[-3, 0, 0], [2, 1, 0], [3, 0, 3]])
print(Q)
c = -np.array([1, -2, 3])
print(c)
b = 0.0

Q_comb = -np.array([[-2, 0, 0], [2, -1, 0], [3, 0, 6]])
Q_2 = -np.array([[1, 0], [0, 2]])
Q_2_full = np.array([[1, 3], [3, 2]])

Q_big = np.random.rand(8,8)
Q_big_sym = 10*(Q_big + Q_big.T)

big_c = 3*(np.random.rand(8)-0.5)

qubo_problem = problems.QUBO(Q, c, b)
qubo_problem_comb = problems.QUBO(Q_comb)
qubo_problem2 = problems.QUBO(Q_2)
qubo_problem2_full = problems.QUBO(Q_2_full)

qubo_big_full_sym = problems.QUBO(Q_big_sym)
qubo_big_full_asym = problems.QUBO(Q_big)

qubo_big_asym_with_c = problems.QUBO(Q_big, big_c)


[[ 3  0  0]
 [-2 -1  0]
 [-3  0 -3]]
[-1  2 -3]


In [3]:
bitstring = util.validation._bitstring
n = 3
for i in range(2**n):
    bs = bitstring(i, n)
    print(bs, qubo_problem.cost(bs), qubo_problem_comb.cost(bs))

for i in range(2**2):
    bs = bitstring(i, 2)
    print(bs, qubo_problem2.cost(bs), qubo_problem2_full.cost(bs))

000 -0.0 -0.0
001 6.0 6.0
010 -1.0 -1.0
011 5.0 5.0
100 -2.0 -2.0
101 7.0 7.0
110 -1.0 -1.0
111 8.0 8.0
00 -0.0 -0.0
01 2.0 -2.0
10 1.0 -1.0
11 3.0 -9.0


In [4]:

qaoa = QAOA(
    initialstate=initialstates.Plus(),
    problem=qubo_problem,
    mixer=mixers.X()
    )
qaoa2 = QAOA(
    initialstate=initialstates.Plus(),
    problem=qubo_problem2,
    mixer=mixers.X()
    )
qaoa2_full = QAOA(
    initialstate=initialstates.Plus(),
    problem=qubo_problem2_full,
    mixer=mixers.X()
    )

qaoa_big_sym = QAOA(
    initialstate=initialstates.Plus(),
    problem=qubo_big_full_sym,
    mixer=mixers.X()
    )
qaoa_big_asym = QAOA(
    initialstate=initialstates.Plus(),
    problem=qubo_big_full_asym,
    mixer=mixers.X()
    )
qaoa_comb = QAOA(
    initialstate=initialstates.Plus(),
    problem=qubo_problem_comb,
    mixer=mixers.X()
    )

qaoa_big_asym_with_c = QAOA(
    initialstate=initialstates.Plus(),
    problem=qubo_big_asym_with_c,
    mixer=mixers.X()
)

# qaoa.validate_circuit()

In [5]:
qaoa.validate_circuit()

2025-09-11 14:47:23 [info     ] Creating parameterized cirquit for generic QUBO problem file=qaoa.problems.qubo_problem


(np.True_,
 {'n_qubits': 3,
  'max_magnitude_error': 2.220446049250313e-16,
  'max_phase_error_rad_after_global': 1.5175952767906853e-16,
  'global_phase_rad': -2.75})

In [6]:
qaoa2.problem.QUBO_Q

array([[-1,  0],
       [ 0, -2]])

In [7]:
qaoa2_full.problem.QUBO_Q

array([[1, 3],
       [3, 2]])

In [8]:
qaoa2.validate_circuit()

2025-09-11 14:47:23 [info     ] Creating parameterized cirquit for generic QUBO problem file=qaoa.problems.qubo_problem


(np.True_,
 {'n_qubits': 2,
  'max_magnitude_error': 2.220446049250313e-16,
  'max_phase_error_rad_after_global': 1.245872138710481e-16,
  'global_phase_rad': -1.5})

In [9]:
qaoa2_full.validate_circuit()

2025-09-11 14:47:23 [info     ] Creating parameterized cirquit for generic QUBO problem file=qaoa.problems.qubo_problem


(np.True_,
 {'n_qubits': 2,
  'max_magnitude_error': 0.0,
  'max_phase_error_rad_after_global': 2.802661385663196e-16,
  'global_phase_rad': 3.0})

In [10]:
qaoa_big_sym.validate_circuit()

2025-09-11 14:47:23 [info     ] Creating parameterized cirquit for generic QUBO problem file=qaoa.problems.qubo_problem


(np.True_,
 {'n_qubits': 8,
  'max_magnitude_error': 7.771561172376096e-16,
  'max_phase_error_rad_after_global': 1.3361715807303482e-13,
  'global_phase_rad': 1.4605132598486603})

In [11]:
qaoa_comb.validate_circuit()

2025-09-11 14:47:23 [info     ] Creating parameterized cirquit for generic QUBO problem file=qaoa.problems.qubo_problem


(np.True_,
 {'n_qubits': 3,
  'max_magnitude_error': 2.220446049250313e-16,
  'max_phase_error_rad_after_global': 1.5175952767906853e-16,
  'global_phase_rad': -2.75})

In [12]:
qaoa_big_asym.validate_circuit()

2025-09-11 14:47:24 [info     ] Creating parameterized cirquit for generic QUBO problem file=qaoa.problems.qubo_problem


(np.True_,
 {'n_qubits': 8,
  'max_magnitude_error': 1.1102230246251565e-15,
  'max_phase_error_rad_after_global': 4.415714755339061e-15,
  'global_phase_rad': -3.0685669905973607})

In [13]:
qaoa_big_asym_with_c.validate_circuit()

2025-09-11 14:47:24 [info     ] Creating parameterized cirquit for generic QUBO problem file=qaoa.problems.qubo_problem


(np.True_,
 {'n_qubits': 8,
  'max_magnitude_error': 1.1102230246251565e-15,
  'max_phase_error_rad_after_global': 3.902016428558049e-15,
  'global_phase_rad': 2.0408355078454874})